### ISSUE TITLE
Add correct contact info and address of the venue

### ISSUE THREAD

**Issue by valerymelou** [DevOfFuture/dof-conf#6]
The venue section still have some placeholder values. We should probably fix that now.

**Comment by sdmg15** [comment]
Okay sharing the location with you tomorrow morning

**Comment by valerymelou** [comment]
Was referring to the contact info (telephone number) and address in the Venue section. Are they correct on the site now? But yeah send me the location too, for the map.

**Comment by sdmg15** [comment]
We can remove the phone and just put the mail address "devoffuture at gmail dot com"
